### ISSUE TITLE
download zip?

### ISSUE THREAD

**Issue by dbox** [misega/HTML5-Banners#3]
Hey-

I sent you a tweet thanking you for making this awesome tool, but I'll reiterate it here. Really great work.

Feature idea: Wondering if it would be possible to add a step to the `gulp review` process that generates a zip of all the `banner` folders. Then that could easily be reference with a hyperlink on the review page. 

Just a thought. Happy to attempt this with a PR if you're interested.

Thanks again! 🙏

**Comment by misega** [comment]
Thank you! I appreciate the feedback.
I can add a zip file that is a collection of all the banners. Plus, it might be beneficial to add a zip file of each banner, ready for download/distribution, with each tab on the review site.

**Comment by dbox** [comment]
💯  Will be so nice. Let me know if you want any help.
